Chapters 7 to 28
YanethM/ruby_path_p1 pull request #1
Opened 2022-08-19 10:06 UTC by YanethM

2022-08-19 13:08 UTC, MrJuanGaviriaK requested changes
Hi, I left one minor comment below.

2022-08-19 13:08 UTC, MrJuanGaviriaK commented on index.html
> +<h1>Yaneth, Mejía</h1><div><p>lorem input</p></div>
Pelase, you should have an empty line at the end of each file.

2022-08-19 21:38 UTC, YanethM commented on index.html
> +<h1>Yaneth, Mejía</h1><div><p>lorem input</p></div>
the missing line break was added to the file

2022-08-22 11:36 UTC, MrJuanGaviriaK approved these changes

2022-08-22 19:17 UTC, merged